# from latest dag image


# Switch to root
# add needed folders and permission
# switch back to non-root

# activate venv


COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Run the correct jupyterhub command, pointing to the config file in the hub-deploy yaml